### ISSUE TITLE
UnusedUseSniff doesn't detect return value type hints

### ISSUE THREAD

**Issue by adrianheine** [wmde/WikibaseCodeSniffer#35]
Example:
```php
namespace A;

use X;

interface I {
  public function foo(): X;
}
```

You could have a look at the extremely more complex https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Helpers/ReferencedNameHelper.php for reference.

**Comment by thiemowmde** [comment]
Oh, PHP7? Are you using this codesniffer ruleset with a PHP7-only codebase already? I believe I need to check quite some sniffs here and in the upstream MediaWiki codesniffer for PHP7-compatibility, but wanted to do this when the need arises.

**Comment by adrianheine** [comment]
Yeah, I get to do the nice things :) https://github.com/adrianheine/mw-wikibase-forms

**Comment by JeroenDeDauw** [comment]
>  PHP7-only codebase already

"already" :D

https://secure.php.net/supported-versions.php
