### ISSUE TITLE
Namespaces.UnusedUse.Found fails for return types

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseCodeSniffer#50]
This change https://gerrit.wikimedia.org/r/c/mediawiki/extensions/WikibaseQualityConstraints/+/470586/1/src/ConstraintsServices.php causes these errors https://integration.wikimedia.org/ci/job/quibble-composer-mysql-hhvm-docker/2823/consoleFull

It seems that `Wikibase.Namespaces.UnusedUse.Found` does not hold into account return types and is now thus effectively broken.

**Comment by thiemowmde** [comment]
This got fixed a long time ago via #35 and #36. The WikibaseQualityConstraints codebase is just using an outdated version of WikibaseCodeSniffer.

**Comment by JeroenDeDauw** [comment]
@thiemowmde is that kept track of somewhere?

**Comment by thiemowmde** [comment]
What should be kept track of where?

**Comment by JeroenDeDauw** [comment]
WikibaseQualityConstraints using an outdated version. And yes, where this should be is my question.

**Comment by thiemowmde** [comment]
I'm afraid I still don't get the question. If there is no Phabricator ticket for this, you can create one and propose it for the Wikidata team to pick up.
